#!/bin/bash

if [ $1 == 'miro' ]; then
  printf "\e[38;5;169mMiRo mode. \e[38;5;015m (Run 'robot_switch tb3' to change mode)\n"
  echo "miro" > ~/.current_robot
  exec bash
elif [ $1 == 'tb3' ]; then
  printf "\e[38;5;9mTurtleBot3 Waffle mode. \e[38;5;015m (Run 'robot_switch miro' to change mode)\n"
  echo "turtlebot" > ~/.current_robot
  exec bash
else
  printf "Not a valid input, use 'miro' or 'tb3'\n"
fi
