site_name: "ROS2 Course Assignments for COM2009"
site_url: https://tom-howard.github.io/com2009/
site_description: Practical Robotics Course Assignments for COM2009/3009, with ROS2 and the TurtleBot3 Waffle.  
theme:
  name: material
  icon:
    repo: fontawesome/brands/github
  font: 
    text: Source Sans Pro
    code: Source Code Pro
  palette:
    # Palette toggle for light mode
    - scheme: default
      primary: custom
      accent: custom
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode
    # Palette toggle for dark mode
    - scheme: slate
      primary: deep purple
      accent: cyan
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  custom_dir: overrides

  logo: assets/tuos.png
  favicon: assets/tuos_logo.svg

  features:
    - navigation.tracking
    - navigation.tabs
    # - navigation.expand
    - navigation.top
    - navigation.footer
    - navigation.indexes
    - toc.follow
    - content.code.copy
    - content.code.annotate
    - content.action.edit
    - content.action.view

copyright: >
  <a rel="license" href="http://creativecommons.org/licenses/by-sa/4.0/"><img alt="Creative Commons License" style="border-width:0" src="https://i.creativecommons.org/l/by-sa/4.0/88x31.png" /></a><br /> 
  &copy; <a href="https://www.sheffield.ac.uk/engineering/diamond-engineering/our-staff/tom-howard">Tom Howard</a>, The University of Sheffield, 2025.
repo_url: https://github.com/tom-howard/com2009
repo_name: tom-howard/com2009
edit_uri: ./edit/main/docs

plugins:
  - search
  - awesome-pages
  - git-revision-date-localized:
      enable_creation_date: true
      type: timeago
      enabled: !ENV [CI, false]
  - privacy:
      enabled: !ENV [CI, false]
  - social:
      enabled: !ENV [CI, false]
      cards_layout_options:
        font_family: Noto Sans
  - glightbox

markdown_extensions:
  - admonition
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - toc:
      permalink: true
  - attr_list
  - md_in_html
  - footnotes
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
      clickable_checkbox: true
  - pymdownx.keys
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.tilde
  - pymdownx.caret
  - pymdownx.tabbed:
      alternate_style: true

extra_css:
  - stylesheets/extra.css

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
