#!/bin/bash
# adapted from https://gist.github.com/davejamesmiller/1965569

ask() {
    local prompt default reply

    if [[ ${2:-} = 'Y' ]]; then
        prompt='Y/n'
        default='Y'
    elif [[ ${2:-} = 'N' ]]; then
        prompt='y/N'
        default='N'
    else
        prompt='y/n'
        default=''
    fi

    while true; do

        # Ask the question (not using "read -p" as it uses stderr not stdout)
        echo -n "$1 [$prompt] "

        # Read the answer (use /dev/tty in case stdin is redirected from somewhere else)
        read -r reply </dev/tty

        # Default?
        if [[ -z $reply ]]; then
            reply=$default
        fi

        # Check if the reply is valid
        case "$reply" in
            Y*|y*) return 0 ;;
            N*|n*) return 1 ;;
        esac

    done
}


if [ $1 == 'backup' ]; then
  if [ -f /mnt/u/wsl-ros/ros-backup.tar.gz ]; then
    if ask "Preparing to backup your WSL-ROS environment: This will overwrite your existing WSL-ROS backup. Are you sure you want to continue?"; then
      rosbackup.sh
    else
      echo "Backup cancelled."
    fi
  else
    rosbackup.sh
  fi
elif [ $1 == 'restore' ]; then
  if [ -f /mnt/u/wsl-ros/ros-backup.tar.gz ]; then
    rosrestore.sh
  else
    echo "Unable to restore: A U:\wsl-ros\ros-backup.tar.gz file does not exit."
  fi
else
  echo "$1 is not a valid input, provide either 'backup' or 'restore'"
fi
